version: "3.9"
services:
  api:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - search
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=news
      - POSTGRES_DB=news
    ports:
      - "5433:5432"
  search:
    image: getmeili/meilisearch:v1.4
    environment:
      - MEILI_MASTER_KEY=79218197551724857046
    ports:
      - "7701:7700"
