services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=news
      - POSTGRES_PASSWORD=news
      - POSTGRES_DB=news
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news -d news"]
      interval: 5s
      timeout: 5s
      retries: 5
  search:
    image: getmeili/meilisearch:v1.4
    environment:
      - MEILI_MASTER_KEY=79218197551724857046
    ports:
      - "7701:7700"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7700/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
